apiVersion: ENC[AES256_GCM,data:zC0=,iv:ICkEeJKIex1Ukil55YzACgTrm/FJlUo/gwnVHvNfGuQ=,tag:EfagxCY3+seRBqRzKdiriQ==,type:str]
data:
    client-id: ENC[AES256_GCM,data:eVVkE6aZpdpZYuFm+dKpsoCyRY7L1nyOE1YS1A==,iv:+VA9nOsrLM6da9+KcN/axSO4UYM+xLxyW1OwDmMpNtM=,tag:eqnY58iUoJZne7J1RtPn9Q==,type:str]
    client-secret: ENC[AES256_GCM,data:M3Yj/sjmwzzXcL8PYzGHwWMfjtXF8P3g9sOwfh8Gnk5zjR7ew5R4YiK2obp8hK0jXLcZNDlOeLw=,iv:Oh7fXPYpe1nGdjv2n2dsI6ooWIuKWx65p6YRYLM/VxQ=,tag:2a8QbAnWRGbf9e/PiNTkZw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:auoZDyRJ8gaSvAIfZtJ7Q5DZPuyeZgd/VVHcR+zKDQI=,iv:EhFFoJc//TdIZ1pDR4Dqw1vErMNurNhd/7ktim2GLSs=,tag:RPjbuGxSkt7Os+tsSOtAoQ==,type:str]
kind: ENC[AES256_GCM,data:+85iKRmh,iv:Qk9zypZBqtEmyoBGbVLtNaevdnP9gs6vUGd+J3o2T+4=,tag:YfH6Utktj7wuDaZdy4x1Wg==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:WmeFleCpfQMkMLVjo3MBEp55pQ==,iv:otssegWtzx1HZoFbqIsJ4FGgSpYgDouoUqiK8dAX3JQ=,tag:7EQcQcqkU0SMi2Efkbf5bQ==,type:str]
    namespace: ENC[AES256_GCM,data:Ep6qpKZFcg==,iv:l6yKPZFVk8KGgaG5rxrE3e5xdI1VQPRiFR0+RcYpSqU=,tag:MxWEXVrEJNt2QmVjC/cHPw==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/raspbernetes/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2020-11-13T09:54:46Z'
        enc: CiQAesqCORh4J5LHamzsTWEQCz8V3/9ECpmcYFup/KmUlc8FDgUSSQA2cmGUCw9Q6HeXsQ/LUyJ1kzvICX32tETCRaWjQ/KvUvUt4FW5hWr7Rpio+scAABGZrI7V3ED3XcJxCDvwL9hlZ/Ca0+5XHPU=
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-11-13T09:54:48Z'
    mac: ENC[AES256_GCM,data:5TYpst4FQUaZ9aSvz/s0RiUrWBNxHwCY6Q7wYYN6NQh/ZKnUwybgEAowzGd8jUzE38/9RwOC1FDmo8e6QWeuHc66wua6l1jgK3Zul2jIOxaUxVtu/sGi0w8XZI4kV/D5PU9ypVPV8yqg/Bv5CGnWXU1jnjG7W+7dgL8V5mc7LDw=,iv:imJlR9eNPtyc+VXm6elld60KVNuPm4ctEkDcs71QtLo=,tag:HJcjRvpLsKelRJHFT3dwHg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
