# https://docs.projectcalico.org/maintenance/enabling-bpf
---
apiVersion: crd.projectcalico.org/v1
kind: FelixConfiguration
metadata:
  name: default
spec:
  bpfEnabled: true
  bpfExternalServiceMode: 'DSR'
  bpfLogLevel: ''
  ipipEnabled: true
  logSeverityScreen: Info
  prometheusMetricsEnabled: true # https://docs.projectcalico.org/maintenance/monitor/monitor-component-metrics
  reportingInterval: 0s
  # sidecarAccelerationEnabled: true # https://docs.projectcalico.org/networking/sidecar-acceleration
  # policySyncPathPrefix: '/var/run/nodeagent' # https://docs.projectcalico.org/security/app-layer-policy
