apiVersion: projectcalico.org/v3
kind: FelixConfiguration
metadata:
  name: default
spec:
  bpfEnabled: true # https://docs.projectcalico.org/maintenance/enabling-bpf
  bpfLogLevel: ''
  ipipEnabled: true
  logSeverityScreen: Info
  prometheusMetricsEnabled: true # https://docs.projectcalico.org/maintenance/monitor/monitor-component-metrics
  reportingInterval: 0s
  sidecarAccelerationEnabled: true # https://docs.projectcalico.org/networking/sidecar-acceleration
  policySyncPathPrefix: '/var/run/nodeagent' # https://docs.projectcalico.org/security/app-layer-policy
