# https://github.com/cilium/cilium/blob/v1.9.0-rc0/install/kubernetes/cilium/values.yaml
operator:
  image: docker.io/cilium/operator-dev:v1.9.0-rc0
agent:
  image: docker.io/cilium/cilium-dev:v1.9.0-rc0
config:
  enableIdentityMark: false
  disableEnvoyVersionCheck: true
global:
  cni:
    chainingMode: generic-veth
    customConf: true
    configMap: cni-configuration
  tunnel: disabled
  masquerade: false
#   hubble:
#     relay:
#       enabled: true
# hubble-relay:
#   image:
#     name: hubble-relay
#     tag: latest
#     pullPolicy: Always
#   numReplicas: 1
#   servicePort: 80
