apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-creds
  namespace: observability
spec:
  encryptedData:
    admin-password: AgCnOIOdiuRMUwQDLGCxnqKblAekVEqzWITyxHgB0hbpzoU43GmtYIBkZkRDTS0wOWo+Q3aU3H97u47cBILkqTXOaVZLtlmSv9MQZvuIEelLs+8CanRuJyiYhwnvu+iLIqOC3odO5ZqTKvbcAZkQaS7A0y8V9Pi0yf3TzgLKkYkAH6tETs3z6MsxjF8DpYcNJr/yj3evI/YmZw3pKlWazU1Hya7Ep3Uvakl1H+SNhZddkoHcnwg62P47w2ReGOglAyU0f2e1stPQi0Da721E6oyguzOctelL7P7Ik7cTgP6TIhBahDM6S5X4bdHM7Ubd9uc8jG4bLoZise/p2eIV/+Wle7EqQFY+etiRMq5ut6s+gp+MIzYQxDmcML8cdNRSTdcP41H8+0Jf0r9SNsISOzDI2U1yLsH4U+y+MH4jLvn80PWmjqalw9SD+/SoWVSV52TBx2xFdBCoMWAtWY6tHoGX1wKhtYn93CAY1nSotQ75V22odbnx4FFISk/kbbMLN0SKGagq9oqCS/fipTGYnMhPTLaIFv5bghHgg0rdjZJYsazs+Geb4z2weIr/fcCdy7QQb2uN78cAlTii7i+EwIXDP6Zt9+qSlogjGHd1OWpVdnGVc5hCyaI42CY0N21U6pz2brIq7O2L+AR3Rj7E2yGRxagdtefIDH3n57vs45ZRF3kNu/SBG6FRvT1jC+FFmIQq4Z1vLahmpQ==
    admin-user: AgCWQIeKgsKd8YNW15enS5hQjE8xL7iHmwAOGv2ZHvcf5ZgXAAS4rOr4Iej+Ktk1XdV3oO+9KzKoKDMEXrbp5pexe0WaOkqrQ+jdVPCI8U5Ql3VjgP0fO31kPVh5L2LO0OGcHVdsBEuWQVQ9YsHvDchZluJIXVunRk8fROvrvBT9UMr8sbqxO++YHjt6YE37EWDLb6fYCvDyc3IDsp7sROTApYTN9UBcEYh3vbSRgL/TgvAG6+8PCx4Hwrau8xc1nXefVl24+LUryELP1YMhGfmIbXVC+42uPeT3s5jTT1m0lYrypB9b6y0ZW51cwDWNrPhMsqnZiSv1h7yMYtiQjWpkXnLooeASAYYhrbCtfhMPaHRgU+oz0JuY9kEFxqkNi8043najwUI9w81Icmxvs3YCyI13psxm7xeFOU+U/ej0RQa99ggKpNcjlN6w6ZHEVtCC9z/wPT8nKwcxq3isptc46ztM+SWKGH4E3Bv+Qe2SE+oY0gDmhkPqDEDtQQVfDD9yK7LVir6kugXXn6mBfCDEpdZCEQ55CG9vdj+0w8ypu+M1iqS+sksnGGotG2aXEi0xwY1Ypl8zkBK/zXPPlfq2gbBbOY62Z1v35TTfRJNbM59ctFqRk1ETMUS6H58OVGIJZV8UWJ+U9y/3m28lfM1dH4Q9Vz821SAgRum6JKXyzuCO9my3VzTvpGArBAag57gp3jP4kA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-creds
      namespace: observability
