---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  CLUSTER: cluster-0
  GITHUB_USER: xunholy
  GITHUB_REPO: k8s-gitops
  GITHUB_BRANCH: main

includes:
  core: .taskfiles/Core
  flux: .taskfiles/Flux
  mkdocs: .taskfiles/Mkdocs
  sidero: .taskfiles/Sidero
  talos: .taskfiles/Talos

tasks:
  flux:
    desc: "Install Fluxv2 into a cluster"
    cmds:
      - task: flux:secrets
      - task: flux:bootstrap
