---
# Source: origin-ca-issuer/templates/issuer-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-origin-ca-issuer-controller
  labels:
    app: origin-ca-issuer
    app.kubernetes.io/name: origin-ca-issuer
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "controller"
    helm.sh/chart: origin-ca-issuer-0.5.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default-origin-ca-issuer-controller
subjects:
  - name: default-origin-ca-issuer
    namespace: "network"
    kind: ServiceAccount
