---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
  annotations:
    fluxcd.io/ignore: 'false'
    fluxcd.io/automated: 'false'
spec:
  releaseName: loki
  helmVersion: v3
  chart:
    repository: https://grafana.github.io/loki/charts
    name: loki-stack
    version: 0.38.2
  values:
    loki:
      enabled: true
      serviceMonitor:
        enabled: true
    promtail:
      enabled: true
      serviceMonitor:
        enabled: true
    fluent-bit:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false
