---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dex
  namespace: flux-system
  labels:
    substitution.flux/enabled: true
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: "./namespaces/base/network-system/dex/app"
  prune: true
  wait: true
  sourceRef:
    kind: OCIRepository
    name: cluster
  dependsOn:
    - name: istiod
      namespace: flux-system
