---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 5.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 10m
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    hostNetwork: true
    extraEnv:
      TZ: 'Australia/Melbourne'
    persistence:
      enabled: true
      size: 5Gi
      storageClass: openebs-cstor-sparse
    service:
      portName: http-api
    vscode:
      enabled: true
      image:
        repository: codercom/code-server
        tag: 3.7.1
      extraEnv:
        HASS_SERVER: 'http://localhost:8123'
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
