apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./operator-system/configconnector-operator.yaml


patches:
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: not-used
      spec:
        template:
          spec:
            nodeSelector:
              beta.kubernetes.io/arch: amd64
    target:
      kind: StatefulSet
      labelSelector: cnrm.cloud.google.com/component=configconnector-operator
