---
helm:
  versions: v3

image:
  repository: docker.io/raspbernetes/helm-operator
  tag: v1.2.0

chartsSyncInterval: "3m"
statusUpdateInterval: "30s"
createCRD: true

rbac:
  pspEnabled: true

git:
  pollInterval: "1800m"
  ssh:
    secretName: flux-git-ssh-private-key

resources:
  limits:
    cpu: 0.5
    memory: 2Gi
  requests:
    cpu: 50m
    memory: 64Mi

prometheus:
  enabled: true
  serviceMonitor:
    # Enables ServiceMonitor creation for the Prometheus Operator
    create: true
    interval:
    scrapeTimeout:
    namespace:
    additionalLabels: {}

dashboards:
  # If enabled, helm-operator will create a configmap with a dashboard in json that's going to be picked up by grafana
  # See https://github.com/helm/charts/tree/master/stable/grafana#configuration - `sidecar.dashboards.enabled`
  enabled: true
