---
helm:
  versions: v3

image:
  repository: docker.io/raspbernetes/helm-operator
  tag: v1.0.0-rc9

chartsSyncInterval: "5m"
statusUpdateInterval: "60s"

git:
  ssh:
    secretName: flux-git-deploy
