---
helm:
  versions: v3

image:
  repository: docker.io/raspbernetes/helm-operator
  tag: v1.0.0-rc9

chartsSyncInterval: "3m"
statusUpdateInterval: "30s"
createCRD: true

rbac:
  pspEnabled: true
git:
  pollInterval: "1800m"
  ssh:
    secretName: flux-git-deploy
