---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: kubecon-mgmt
  name: cluster-00
spec:
  description: Management Cluster.
  enableAutopilot: true
  location: us-west1
  releaseChannel:
    channel: RAPID
  addonsConfig:
    # TODO: Error 400: Addons {"config-connector"} are not supported for Autopilot clusters.
    # configConnectorConfig:
    #   enabled: true
    gkeBackupAgentConfig:
      enabled: true
  workloadIdentityConfig:
    # Workload Identity supports only a single namespace based on your project name.
    workloadPool: kubecon-mgmt.svc.id.goog
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeature
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: kubecon-mgmt
  name: gkehubfeature-sample-mcifeature
spec:
  projectRef:
    name: kubecon-mgmt
  location: global
  # The resourceID must be "multiclusteringress" if you want to use multi-cluster
  # ingress feature.
  resourceID: multiclusteringress
  spec:
    multiclusteringress:
      configMembershipRef:
        name: cluster-00

export CLUSTER_LOCATION=us-west1
export CLUSTER_NAME=cluster-00
export PROJECT_ID=kubecon-mgmt
gcloud container fleet memberships register ${CLUSTER_NAME} --project ${PROJECT_ID}\
  --gke-cluster=${CLUSTER_LOCATION}/${CLUSTER_NAME} \
  --enable-workload-identity
