---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: k8s-gitops
  namespace: flux-system
spec:
  interval: 5m
  ref:
    branch: main
  url: https://github.com/raspbernetes/k8s-gitops.git
  ignore: |
    # exclude all
    /*
    # include deploy dir
    !/cluster/
    /cluster/**/*.md
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: k8s-gitops
  namespace: flux-system
spec:
  interval: 5m
  path: './namespaces/production'
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  prune: true
