---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: openfaas
  namespace: openfaas
  annotations:
    fluxcd.io/ignore: 'false'
    fluxcd.io/automated: 'false'
spec:
  releaseName: openfaas
  helmVersion: v3
  chart:
    repository: https://openfaas.github.io/faas-netes/
    name: openfaas
    version: 5.8.8
  values:
    basic_auth: false
    psp: true
    gateway:
      image: openfaas/gateway:0.18.17-arm64
      directFunctions: true
    oauth2Plugin:
      enabled: false
    faasnetes:
      image: openfaas/faas-netes:0.10.5-arm64
    operator:
      image: openfaas/faas-netes:0.10.5-arm64
      create: false
    queueWorker:
      image: openfaas/queue-worker:0.11.0-arm64
    prometheus:
      create: false
    alertmanager:
      create: false
    faasIdler:
      image: openfaas/faas-idler:0.3.0-arm64
    basicAuthPlugin:
      image: openfaas/basic-auth-plugin:0.18.17-arm64
      replicas: 1
    ingressOperator:
      create: false
    nodeSelector:
      beta.kubernetes.io/arch: arm64
