---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: k8s-gitops
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
  suspend: false
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: helmreleases
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: error
  eventSources:
    - kind: HelmRelease
      namespace: 'observability'
      name: '*'
    - kind: HelmRelease
      namespace: 'network'
      name: '*'
    - kind: HelmRelease
      namespace: 'kube-system'
      name: '*'
    - kind: HelmRelease
      namespace: 'backups'
      name: '*'
    - kind: HelmRelease
      namespace: 'litmus'
      name: '*'
    - kind: HelmRelease
      namespace: 'openebs'
      name: '*'
  suspend: false
