---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured-charts
        namespace: gotk-system
      interval: 5m
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 1m
    cleanupOnFail: true
  # Depends on kube-prometheus-stack due to service monitor resources.
  dependsOn:
    - name: kube-prometheus-stack
      namespace: observability
  values:
    image:
      repository: raspbernetes/kured
      tag: 1.5.0
    service:
      create: true
    metrics:
      create: true
