---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/applications/istio/flux-kustomize.yaml
  - ../../base/applications/istio-operator/flux-kustomize.yaml
  - ../../base/crds/cert-manager
  - ../../base/crds/kube-prometheus-stack.yaml
  - ../../base/crds/openebs-cstor.yaml
  - ../../base/crds/openebs-ndm.yaml
  - ../../base/crds/sealed-secrets.yaml
# patchesStrategicMerge:
#   - patch.istio.yaml

