# https://github.com/coredns/helm
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: coredns-charts
  namespace: flux-system
spec:
  interval: 24h
  url: https://coredns.github.io/helm
  timeout: 3m
