---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: network
  annotations:
    fluxcd.io/ignore: 'false'
    fluxcd.io/automated: 'false'
spec:
  releaseName: external-dns
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: external-dns
    version: 3.3.0
  values:
    image:
      registry: docker.io
      repository: raspbernetes/external-dns
      tag: v0.7.3
      pullPolicy: IfNotPresent
    provider: cloudflare
    policy: upsert-only
    registry: 'txt'
    replicas: 1
    logLevel: debug
    rbac:
      create: true
      pspEnabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: observability
    crd:
      create: true
    sources:
      - service
      - ingress
      - istio-gateway
      - istio-virtualservice
    domainFilters:
      - raspbernetes.com
    cloudflare:
      secretName: 'cloudflare-external-dns'
      email: 'michaelfornaro@gmail.com'
      proxied: true
