---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
  creationTimestamp: null
spec:
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: 1.12.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-stable-charts
        namespace: flux-system
      interval: 5m
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 1m
    cleanupOnFail: true
  values:
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: 'letsencrypt-prod'
        nginx.ingress.kubernetes.io/auth-url: 'https://raspbernetes.com/oauth2/auth'
        nginx.ingress.kubernetes.io/auth-signin: 'https://raspbernetes.com/oauth2/start?rd=$escaped_request_uri'
      hosts:
        - sealed-secrets.raspbernetes.com
      path: /v1/cert.pem
      tls:
        - secretName: sealed-secrets.raspbernetes.com-tls
          hosts:
            - sealed-secrets.raspbernetes.com
