---
# Source: origin-ca-issuer/templates/issuer-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-origin-ca-issuer
  namespace: 'network'
  labels:
    app: origin-ca-issuer
    app.kubernetes.io/name: origin-ca-issuer
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: 'controller'
    helm.sh/chart: origin-ca-issuer-0.5.0
