---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: speedtest-prometheus
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: speedtest-prometheus
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 1m
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 1m
    cleanupOnFail: true
  # Depends on having prometheus-operator due to service monitor resources.
  dependsOn:
    - name: kube-prometheus-stack
  values:
    serviceMonitor:
      enabled: true
