apiVersion: projectcalico.org/v3
kind: FelixConfiguration
metadata:
  name: default
spec:
  bpfEnabled: true
  bpfLogLevel: ''
  ipipEnabled: true
  logSeverityScreen: Info
  prometheusMetricsEnabled: true
  reportingInterval: 0s
