---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: speedtest-prometheus
  namespace: observability
  annotations:
    fluxcd.io/ignore: 'false'
    fluxcd.io/automated: 'false'
spec:
  releaseName: speedtest-prometheus
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: speedtest-prometheus
    version: 1.0.1
  values:
    serviceMonitor:
      enabled: true
