---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: acme-crt
  namespace: network
spec:
  secretName: acme-crt-secret
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - raspbernetes.com
    - '*.raspbernetes.com'
