---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/node-feature-discovery/charts
      chart: node-feature-discovery
      version: 0.9.0
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery-chart
        namespace: flux-system
      interval: 10m
  dependsOn:
    - name: cert-manager
      namespace: network
  values:
    master:
      replicaCount: 2
    image:
      repository: docker.io/raspbernetes/node-feature-discovery
      tag: v0.9.0
    worker:
      ## Tolerations to run daemonset on master nodes
      # tolerations:
      #   - effect: 'NoExecute'
      #     operator: 'Exists'
      #   - effect: 'NoSchedule'
      #     operator: 'Exists'
      config: |-
        core:
          sleepInterval: 60s
          sources:
            - custom
            - pci
            - usb
        sources:
          usb:
            deviceClassWhitelist:
              - '02'
              - '03'
              - '0e'
              - 'ef'
              - 'fe'
              - 'ff'
            deviceLabelFields:
              - 'class'
              - 'vendor'
              - 'device'
          custom:
            - name: 'zwave'
              matchOn:
                - usbId:
                    class: ['02']
                    vendor: ['0658']
                    device: ['0200']
            - name: 'intel-gpu'
              matchOn:
                - pciId:
                    class: ['0300']
                    vendor: ['8086']
            - name: 'coral-tpu'
              matchOn:
                - usbId:
                    vendor: ['1a6e', '18d1']
            - name: 'flight-aware'
              matchOn:
                - usbId:
                    class: ['ff']
                    vendor: ['0bda']
                    device: ['2832']
            - name: 'zigbee'
              matchOn:
                - usbId:
                    class: ['ff']
                    vendor: ['1a86']
                    device: ['7523']
            - name: 'ups-apc'
              matchOn:
                - usbId:
                    vendor: ['051d']
                    device: ['0002']
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: apps/v1
            kind: DaemonSet
            metadata:
              name: nfd-worker
              namespace: network
            spec:
              template:
                spec:
                  containers:
                    - name: nfd-worker
                      args:
                        - '--server=nfd-master:8080'
                        - '--ca-file=/etc/kubernetes/node-feature-discovery/certs/ca.crt'
                        - '--key-file=/etc/kubernetes/node-feature-discovery/certs/tls.key'
                        - '--cert-file=/etc/kubernetes/node-feature-discovery/certs/tls.crt'
                      volumeMounts:
                        - name: nfd-worker-cert
                          mountPath: '/etc/kubernetes/node-feature-discovery/certs'
                          readOnly: true
                  volumes:
                    - name: nfd-worker-cert
                      secret:
                        secretName: nfd-worker-cert
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: nfd-master
              namespace: network
            spec:
              template:
                spec:
                  containers:
                    - name: nfd-master
                      args:
                        - '--ca-file=/etc/kubernetes/node-feature-discovery/certs/ca.crt'
                        - '--key-file=/etc/kubernetes/node-feature-discovery/certs/tls.key'
                        - '--cert-file=/etc/kubernetes/node-feature-discovery/certs/tls.crt'
                      volumeMounts:
                        - name: nfd-master-cert
                          mountPath: '/etc/kubernetes/node-feature-discovery/certs'
                          readOnly: true
                  volumes:
                    - name: nfd-master-cert
                      secret:
                        secretName: nfd-master-cert
