apiVersion: v1
data:
  client-id: b2F1dGgyLXByb3h5
  client-secret: clM4RGVvS05LUHZrakhqYjY0dFg=
  cookie-secret: cTBCU251Q3AyUTJLb0luUm9Nc3Y=
kind: Secret
metadata:
  creationTimestamp: null
  name: oauth2-proxy-dex
  namespace: network
