---
# REQUIRED: Increase the number of reconciliations that can be performed in parallel and bump the resources limits
# https://fluxcd.io/flux/cheatsheets/bootstrap/#increase-the-number-of-workers
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --concurrent=5
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --kube-api-qps=50
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --kube-api-burst=100
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --requeue-dependency=30s
# REQUIRED: CPU limits should be removed
- op: remove
  path: /spec/template/spec/containers/0/resources/limits/cpu
