---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: 'false'
    fluxcd.io/automated: 'false'
spec:
  releaseName: gatekeeper-operator
  helmVersion: v3
  rollback:
    enable: false
  chart:
    git: git@github.com:open-policy-agent/gatekeeper.git
    path: chart/gatekeeper-operator
    ref: master
  values:
    image:
      repository: docker.io/raspbernetes/gatekeeper
      release: v3.1.0-beta.8
