apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB2gL54vAEp0AvnyQ2Oc334OnjeJRFuNddDbi1OmCXL9OsaB1tBEEgPNq7c5qT37lf1ejQ+OK1A4FzFfBmF8AXACjXEziHPWS0hgQ2VFVW0PSCZ+YlQ2UKsfGUP037pFVVqkO8k4xXRJaDvRCbe+y5uI0hPzrtVeJSG/IMVLPpyPYcHbBJWC7UQ2YuTel6+R3oSwT4nOLQctzghAkdNvukzsklpoKA0WlUEpxcEil+E4860kQ4WQc1ZlfAaiPchZvJE2+0CClPrmHMQ6MFW/LNwcCbJaasspPrCrIzRmvS2naoR3RzfjggH++dbf8oO9/ICNpoqIr4GtiT0OnVsdMJAWDBOaD48imzzYT6+YLBw+ny25cmNr63Hyo5VHWapsOVZIjSRLYYKn2zjAKEvSoJnLpovPZW8zVC7DX0NmPgpmcJJl+iUyJvBbY70AZuwpWRAGWnLizEwfm3gFNYTzDLLHzZnEL9hMBZjT9ySji/L7BV0w/jBB90yCJyxNyoAt/FDhp2EH441NRhzcvQ0hM4qqH+RDZzXTbkWQx3ohdVy/bGoyue55ZQC98i3maIjZDK6NmAhJgIhT3sww38UB/O7MQKFguhioM5ggMQ7wW0IwQq8dInGxP0TIDxclglpUfTMo7a7gUutL1N8sYO0gPTU94GEB0psB6oajP4TEAz1MFQh0poja5slRDvmNt/vSuw6NBSDEDKF3uCn/kHZaIzBJLzuG0iepilxUiImMDMWHXwfLmH3RV5x
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque

