---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./tenants/overlays/cluster-0
  prune: true
  wait: false
  sourceRef:
    kind: OCIRepository
    name: cluster
