apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: vmware-charts
  namespace: gotk-system
spec:
  interval: 24h
  url: https://vmware-tanzu.github.io/helm-charts
  timeout: 3m
