apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: weaveworks-kured-charts
  namespace: gotk-system
spec:
  interval: 24h
  url: https://weaveworks.github.io/kured
  timeout: 3m
