---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: etcd
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: etcd
      version: 5.4.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: docker.io
      repository: raspbernetes/etcd
      tag: latest
    statefulset:
      replicaCount: 1
    auth:
      rbac:
        enabled: false
    persistence:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false
