---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: openebs
  name: openebs
  namespace: storage
spec:
  endpoints:
    - path: /metrics
      port: exporter
  namespaceSelector:
    matchNames:
      - storage
  selector:
    matchLabels:
      openebs.io/cas-type: cstor
      monitoring: volume_exporter_prometheus
