---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-cni
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: "./namespaces/base/istio-system/istio-cni/app"
  prune: true
  wait: false
  sourceRef:
    kind: OCIRepository
    name: cluster
  dependsOn:
    - name: istio-base
      namespace: flux-system
