---
# Source: sealed-secrets/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sealed-secrets-key-admin
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.8.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/version: 0.10.0
rules:
  - apiGroups:
      - ""
    resourceNames:
      - sealed-secrets-key
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - list
---
# Source: sealed-secrets/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sealed-secrets-service-proxier
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.8.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/version: 0.10.0
rules:
- apiGroups:
  - ""
  resourceNames:
  - 'http:sealed-secrets:'
  - sealed-secrets
  resources:
  - services/proxy
  verbs:
  - create
  - get
