---
# Source: sealed-secrets/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sealed-secrets
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.8.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/version: 0.10.0
spec:
  ports:
    - port: 8080
  selector:
    app.kubernetes.io/name: sealed-secrets
