---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dex
  namespace: network
  annotations:
    fluxcd.io/ignore: 'false'
    fluxcd.io/automated: 'false'
spec:
  releaseName: dex
  chart:
    git: git@github.com:mintel/dex-k8s-authenticator.git
    ref: master
    path: charts/dex
    version: 1.2.0
  values:
    image:
      repository: raspbernetes/dex
      tag: v2.24.0
    global:
      deployEnv: prod
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: 'letsencrypt-prod'
        nginx.ingress.kubernetes.io/auth-url: 'https://raspbernetes.com/oauth2/auth'
        nginx.ingress.kubernetes.io/auth-signin: 'https://raspbernetes.com/oauth2/start?rd=$escaped_request_uri'
      hosts:
        - dex.raspbernetes.com
      path: /
      tls:
        - secretName: dex.raspbernetes.com-tls
          hosts:
            - dex.raspbernetes.com
    config:
      issuer: https://dex.raspbernetes.com
      storage:
        type: kubernetes
        config:
          inCluster: true
      web:
        http: 0.0.0.0:5556
        # If enabled, be sure to configure tls settings above, or use a tool
        # such as let-encrypt to manage the certs.
        # Currently this chart does not support both http and https, and the port
        # is fixed to 5556
        #
        # https: 0.0.0.0:5556
        # tlsCert: /etc/dex/tls/tls.crt
        # tlsKey: /etc/dex/tls/tls.key
      frontend:
        theme: 'coreos'
        issuer: 'Example Co'
        issuerUrl: 'https://raspbernetes.com'
        logoUrl: https://example.com/images/logo-250x25.png
      expiry:
        signingKeys: '6h'
        idTokens: '24h'
      logger:
        level: debug
        format: json
      oauth2:
        responseTypes: ['code', 'token', 'id_token']
        skipApprovalScreen: true
      # Remember you can have multiple connectors of the same 'type' (with different 'id's)
      # If you need e.g. logins with groups for two different Microsoft 'tenants'
      connectors:
        # GitHub configure 'OAuth Apps' -> 'New OAuth App', add callback URL
        # https://github.com/settings/developers
        - type: github
          id: github
          name: GitHub
          config:
            clientID: REDACTED
            clientSecret: REDACTED
            redirectURI: https://dex.raspbernetes.com/callback
            # 'orgs' can be used to map groups from Github
            # https://github.com/coreos/dex/blob/master/Documentation/connectors/github.md
            orgs:
              - name: raspbernetes
      # The 'name' must match the k8s API server's 'oidc-client-id'
      staticClients:
        - id: oauth2-proxy
          name: 'oauth2-proxy'
          secret: REDACTED
          redirectURIs:
            - 'https://kiali.raspbernetes.com/oauth2/callback'
        - id: grafana
          name: 'grafana'
          secret: 'REDACTED'
          redirectURIs:
            - https://grafana.raspbernetes.com/login/generic_oauth
