apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: helm-operator
    chart: helm-operator-1.1.0
    heritage: Helm
    release: default
  name: default-helm-operator
  namespace: flux
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: helm-operator
    chart: helm-operator-1.1.0
    heritage: Helm
    release: default
  name: default-helm-operator
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: helm-operator
    chart: helm-operator-1.1.0
    heritage: Helm
    release: default
  name: default-helm-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default-helm-operator
subjects:
  - kind: ServiceAccount
    name: default-helm-operator
    namespace: flux
---
apiVersion: v1
data:
  config: |
    apiVersion: v1
    clusters: []
    contexts:
    - context:
        cluster: ""
        namespace: default
        user: ""
      name: default
    current-context: default
    kind: Config
    preferences: {}
    users: []
kind: ConfigMap
metadata:
  name: default-helm-operator-kube-config
  namespace: flux
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: helm-operator
    chart: helm-operator-1.1.0
    heritage: Helm
    release: default
  name: default-helm-operator
  namespace: flux
spec:
  ports:
    - name: http
      port: 3030
      protocol: TCP
      targetPort: http
  selector:
    app: helm-operator
    release: default
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helm-operator
    chart: helm-operator-1.1.0
    heritage: Helm
    release: default
  name: default-helm-operator
  namespace: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-operator
      release: default
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/repositories: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      labels:
        app: helm-operator
        release: default
    spec:
      containers:
        - args:
            - --enabled-helm-versions=v3
            - --log-format=fmt
            - --git-timeout=20s
            - --git-poll-interval=5m
            - --charts-sync-interval=5m
            - --status-update-interval=60s
            - --update-chart-deps=true
            - --log-release-diffs=false
            - --workers=4
            - --tiller-namespace=kube-system
          image: docker.io/raspbernetes/helm-operator:v1.0.0-rc9
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 3030
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: flux-helm-operator
          ports:
            - containerPort: 3030
              name: http
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 3030
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - mountPath: /etc/fluxd/ssh
              name: git-key
              readOnly: true
      serviceAccountName: default-helm-operator
      volumes:
        - name: git-key
          secret:
            defaultMode: 256
            secretName: flux-git-deploy
