---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: 'false'
    fluxcd.io/automated: 'false'
spec:
  releaseName: prometheus-operator
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 8.12.13
  values:
    prometheusOperator:
      enabled: true
      manageCrds: true
      createCustomResource: true
      image:
        repository: raspbernetes/prometheus-operator
        tag: v0.38.1
        pullPolicy: Always
      tlsProxy:
        image:
          repository: raspbernetes/ghostunnel
          tag: v1.5.2
      admissionWebhooks:
        patch:
          image:
            repository: jettech/kube-webhook-certgen
            tag: v1.2.0
      configmapReloadImage:
        repository: jimmidyson/configmap-reload
        tag: v0.3.0
      prometheusConfigReloaderImage:
        repository: raspbernetes/prometheus-operator-config-reloader
        tag: v0.38.1
    alertmanager:
      enabled: true
    grafana:
      enabled: enabled
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: 'letsencrypt-staging'
          nginx.ingress.kubernetes.io/auth-url: 'https://raspbernetes.com/oauth2/auth'
          nginx.ingress.kubernetes.io/auth-signin: 'https://raspbernetes.com/oauth2/start?rd=$escaped_request_uri'
        hosts:
          - grafana.raspbernetes.com
        path: /
        tls:
          - secretName: grafana.raspbernetes.com-tls
            hosts:
              - grafana.raspbernetes.com
      sidecar:
        image: raspbernetes/k8s-sidecar:0.1.144
        imagePullPolicy: Always
    kube-state-metrics:
      image:
        repository: raspbernetes/kube-state-metrics
        tag: v1.9.5
