name: build

on: ['pull_request']

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          path: './install'
          pattern: '*.sh'
          exclude: './.git/*'

      - name: Lint Yaml
        uses: ibiqlik/action-yamllint@v1

      - name: Kubeval
        uses: instrumenta/kubeval-action@master
        with:
          files: 'anthos/'

      - name: Validate Helm Releases
        uses: stefanprodan/hrval-action@v3.2.0
        with:
          helmRelease: anthos/
          helmVersion: v2
          kubernetesVersion: 1.18.2
          ignoreValues: false

      - name: Kube-score
        id: kube-score
        run: |
          result=$(docker run --rm --workdir /github/workspace \
            -v "$(pwd)":/github/workspace \
            zegl/kube-score:latest \
            score $(find ./anthos/ -name '*.yaml') || exit 0)
          result="${result//'%'/'%25'}"
          result="${result//$'\n'/'%0A'}"
          result="${result//$'\r'/'%0D'}"
          echo $result

      - name: Nomos
        run: |
          docker run --rm --workdir /github/workspace \
            -v $(pwd):/github/workspace \
            xunholy/nomos:v1.3.2-stable \
            vet --path /github/workspace/anthos/

  compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Execute Conftest Tests - Table Output
        id: conftest-table
        run: |
          result=$(docker run --rm --workdir /github/workspace \
            -v $(pwd):/github/workspace \
            instrumenta/conftest:v0.18.2 \
            test -o table -p security-policies/policies/ --all-namespaces --combine anthos/ --no-color || exit 0)
          result="${result//'%'/'%25'}"
          result="${result//$'\n'/'%0A'}"
          result="${result//$'\r'/'%0D'}"
          echo $result
          echo "::set-output name=result::$result"

      - name: Execute Conftest Tests - Stdout Output
        id: conftest-stdout
        run: |
          result=$(docker run --rm --workdir /github/workspace \
            -v $(pwd):/github/workspace \
            instrumenta/conftest:v0.18.2 \
            test -o stdout -p security-policies/policies/ --all-namespaces anthos/ --no-color || exit 0)
          result="${result//'%'/'%25'}"
          result="${result//$'\n'/'%0A'}"
          result="${result//$'\r'/'%0D'}"
          echo $result
          echo ::set-output name=result::$result

      - name: Post Results
        uses: unsplash/comment-on-pr@master
        if: ${{ always() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            ## Conftest Test Results
            ```
            ${{ steps.conftest-stdout.outputs.result }}
            ```
          check_for_duplicate_msg: true
