name: build

on: ['pull_request']

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          path: './install'
          pattern: '*.sh'
          exclude: './.git/*'

      - name: Lint Yaml
        uses: ibiqlik/action-yamllint@v1

      - name: Kubeval
        uses: instrumenta/kubeval-action@master
        with:
          files: 'namespaces/'
