name: cluster

on: ['push']

jobs:
  validate:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Validate Sealed Secrets
        run: |
          curl -L -o kubeseal https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.12.5/kubeseal-arm64
          chmod +x kubeseal
          for FILE in $(find . -name '*.encrypted.yaml'); do
            echo "Validating $FILE"
            ./kubeseal --validate < $FILE --controller-name=sealed-secrets
          done
