---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Example: GCP Workload identity Federation"

on:
  workflow_dispatch: {}

jobs:
  connect:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write' # Required for requesting the JWT
      contents: 'read'  # Required for actions/checkout

    steps:
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b' # v4 # Checkout your repository

    # Authenticate to Google Cloud using the workload identity federation
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@55bd3a7c6e2ae7cf1877fd1ccb9d54c0503c457c' # v2
      with:
        create_credentials_file: 'true' # Create a credentials file
        # Set the workload identity provider and service account
        workload_identity_provider: 'projects/970557914270/locations/global/workloadIdentityPools/raspbernetes-oidc-pool/providers/github-provider'
        service_account: 'raspbernetes-oidc-sa@raspbernetes.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@f0990588f1e5b5af6827153b93673613abdc6ec7' # v2

    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud services list
