---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Docs: Release to GitHub pages"

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - ".github/workflows/publish-docs.yaml"
      - '.github/mkdocs/**'
      - 'docs/**'

jobs:
  release-docs:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: .github/mkdocs/mkdocs.yml
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: .github/mkdocs/requirements.txt
