name: Get latest helm release versions

on:
  schedule:
    - cron: '0 10 * * *'

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch cert-manager release version
        run: |
          curl -sL https://api.github.com/repos/jetstack/cert-manager/releases/latest | \
          jq -r ".tag_name" > config/charts/cert-manager/.version

      # sealed-secrets does not keep their releases corresponding with their charts
      # - name: Fetch sealed-secrets release version
      #   run: |
      #     curl -sL https://api.github.com/repos/bitnami-labs/sealed-secrets/releases/latest | \
      #     jq -r ".tag_name" > config/charts/sealed-secrets/.version

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Michael Fornaro'
          git config --global user.email '20387402+xUnholy@users.noreply.github.com'
          git commit -am "Adding new release version" || exit 0
          git push
