name: sealed-secrets

on:
  push:
    paths:
      - '.github/workflows/sealed-secrets.yml'
      - '.secrets/*.yaml'
    branches:
      - main

jobs:
  validate:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Validate Sealed Secrets
        id: sealed-secrets
        run: |
          sudo docker run --rm --workdir /github/workspace \
            -v $(pwd):/github/workspace \
            -v $HOME/.kube/:/github/workspace/.kube/ \
            docker.io/raspbernetes/builder:latest \
            build/validate.sh

      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Kubernetes Conftest Validation 🖌  \`${{ steps.conftest.outcome }}\`

            <details><summary>Show Kubernetes Conftest Report</summary>

            \`\`\`
            ${{ steps.sealed-secrets.outputs.stdout }}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`.\`, Workflow: \`${{ github.workflow }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
