name: sealed-secrets

on:
  push:
    paths:
      - '.github/workflows/sealed-secrets.yml'
      - '.secrets/*.yaml'
    branches:
      - develop

jobs:
  generate:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Validate Sealed Secrets
        run: |
          docker run --rm --workdir /github/workspace \
            -v $(pwd):/github/workspace \
            -v $HOME/.kube/:/github/workspace/.kube/ \
            docker.io/raspbernetes/builder:latest \
            scripts/validate.sh
