image:
  repository: docker.io/raspbernetes/flux

env:
  secretName: flux-git-ssh-private-key

rbac:
  create: true
  pspEnabled: true

git:
  url: git@github.com:raspbernetes/k8s-gitops.git
  readonly: true
  branch: master
  path: namespaces
  secretName: flux-git-ssh-private-key

registry:
  disableScanning: true

# Disabled due to circular dependency with prometheus-operator being deployed via Flux
prometheus:
  enabled: false
  serviceMonitor:
    # Enables ServiceMonitor creation for the Prometheus Operator
    create: false
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux
    additionalLabels: {}

syncGarbageCollection:
  enabled: true
  dry: false

dashboards:
  # If enabled, flux will create a configmap with a dashboard in json that's going to be picked up by grafana
  # See https://github.com/helm/charts/tree/master/stable/grafana#configuration - `sidecar.dashboards.enabled`
  enabled: true
  # # The namespace where the dashboard is deployed, defaults to the installation namespace
  # namespace:
  # # The prefix of the generated configmaps
  # nameprefix: dashboard
